### ISSUE TITLE
Cannot create sample app

### ISSUE THREAD

**Issue by dgrumieaux** [Alfresco/generator-ng2-alfresco-app#23]
Followed prerequisite instructions (https://github.com/Alfresco/alfresco-ng2-components/blob/master/PREREQUISITES.md) and followed instructions from Wiki. 

Data:

```
$npm install

> sample-app-alpha@0.1.0 postinstall /home/dgrumieaux/dev/clients/tsg/projects/alfresco_angular_poc/sample-app-alpha
> typings install

typings WARN deprecated 9/14/2016: "registry:dt/core-js#0.0.0+20160317120654" is deprecated (updated, replaced or removed)
typings WARN deprecated 10/19/2016: "registry:dt/node#4.0.0+20160509154515" is deprecated (updated, replaced or removed)
typings WARN deprecated 10/3/2016: "registry:dt/jasmine#2.2.0+20160505161446" is deprecated (updated, replaced or removed)

├── core-js (global)
├── jasmine (global)
└── node (global)

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.14: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN ng2-translate@2.2.0 requires a peer of @angular/common@2.0.0-rc.2 but none was installed.
npm WARN ng2-translate@2.2.0 requires a peer of @angular/compiler@2.0.0-rc.2 but none was installed.
npm WARN ng2-translate@2.2.0 requires a peer of @angular/core@2.0.0-rc.2 but none was installed.
npm WARN ng2-translate@2.2.0 requires a peer of @angular/http@2.0.0-rc.2 but none was installed.

```

$npm -v
3.10.8

$node -v
v6.9.1

[npm-debug.log](https://github.com/Alfresco/generator-ng2-alfresco-app/files/544806/npm-debug.txt)
[package.json](https://github.com/Alfresco/generator-ng2-alfresco-app/files/544812/package.txt)

**Comment by magemello** [comment]
Hi, can you try to run first:

`npm run build 
`

and then

`npm run tsc:w`

**Comment by dgrumieaux** [comment]
```
> sample-app-alpha@0.1.0 build /home/dgrumieaux/dev/clients/tsg/projects/alfresco_angular_poc/sample-app-alpha
> npm run tslint && npm run tsc && npm run license-check


> sample-app-alpha@0.1.0 tslint /home/dgrumieaux/dev/clients/tsg/projects/alfresco_angular_poc/sample-app-alpha
> tslint -c tslint.json *.ts && tslint -c tslint.json 'app/{,**/}**.ts'


> sample-app-alpha@0.1.0 tsc /home/dgrumieaux/dev/clients/tsg/projects/alfresco_angular_poc/sample-app-alpha
> tsc


> sample-app-alpha@0.1.0 license-check /home/dgrumieaux/dev/clients/tsg/projects/alfresco_angular_poc/sample-app-alpha
> echo 'license check is disabled'

license check is disabled
```

```
> sample-app-alpha@0.1.0 tsc:w /home/dgrumieaux/dev/clients/tsg/projects/alfresco_angular_poc/sample-app-alpha
> tsc -w

9:58:00 AM - Compilation complete. Watching for file changes.
```

No errors, watch is working as expected. npm start is still erroring though.

**Comment by magemello** [comment]
can you try to run again in the order:

```
npm clean

npm install

npm start
```
and then post here the eventual error?

**Comment by dgrumieaux** [comment]
There is no `npm clean` command, but here's the error I'm seeing after executing `npm install` and `npm start`:
```
license check is disabled
[0] 
[0] > sample-app-alpha@0.1.0 tsc:w /home/dgrumieaux/dev/clients/tsg/projects/alfresco_angular_poc/sample-app-alpha
[0] > tsc -w
[0] 
[1] 
[1] > sample-app-alpha@0.1.0 serve /home/dgrumieaux/dev/clients/tsg/projects/alfresco_angular_poc/sample-app-alpha
[1] > wsrv -o -s -l -p 3000 -x ./server/versions.js
[1] 
[1] Server running at: http://localhost:3000
[1] Opening start page: http://localhost:3000
[1] events.js:160
[1]       throw er; // Unhandled 'error' event
[1]       ^
[1] 
[1] Error: watch /home/dgrumieaux/dev/clients/tsg/projects/alfresco_angular_poc/sample-app-alpha/app/app.component.html ENOSPC
[1]     at exports._errnoException (util.js:1026:11)
[1]     at FSWatcher.start (fs.js:1429:19)
[1]     at Object.fs.watch (fs.js:1456:11)
[1]     at createFsWatchInstance (/home/dgrumieaux/dev/clients/tsg/projects/alfresco_angular_poc/sample-app-alpha/node_modules/chokidar/lib/nodefs-handler.js:37:15)
[1]     at setFsWatchListener (/home/dgrumieaux/dev/clients/tsg/projects/alfresco_angular_poc/sample-app-alpha/node_modules/chokidar/lib/nodefs-handler.js:80:15)
[1]     at FSWatcher.NodeFsHandler._watchWithNodeFs (/home/dgrumieaux/dev/clients/tsg/projects/alfresco_angular_poc/sample-app-alpha/node_modules/chokidar/lib/nodefs-handler.js:228:14)
[1]     at FSWatcher.NodeFsHandler._handleFile (/home/dgrumieaux/dev/clients/tsg/projects/alfresco_angular_poc/sample-app-alpha/node_modules/chokidar/lib/nodefs-handler.js:255:21)
[1]     at FSWatcher.<anonymous> (/home/dgrumieaux/dev/clients/tsg/projects/alfresco_angular_poc/sample-app-alpha/node_modules/chokidar/lib/nodefs-handler.js:473:21)
[1]     at FSReqWrap.oncomplete (fs.js:123:15)
[1] 
[1] npm
[1]  ERR! Linux 3.16.0-77-generic
[1] npm ERR! argv "/home/dgrumieaux/.nvm/versions/node/v6.9.1/bin/node" "/home/dgrumieaux/.nvm/versions/node/v6.9.1/bin/npm" "run" "serve"
[1] npm ERR! node v6.9.1
[1] npm ERR! npm  v3.10.8
[1] npm ERR! code ELIFECYCLE
[1] npm ERR! sample-app-alpha@0.1.0 serve: `wsrv -o -s -l -p 3000 -x ./server/versions.js`
[1] npm ERR! Exit status 1
[1] npm ERR! 
[1] npm ERR! Failed at the sample-app-alpha@0.1.0 serve script 'wsrv -o -s -l -p 3000 -x ./server/versions.js'.
[1] npm ERR! Make sure you have the latest version of node.js and npm installed.
[1] npm ERR!
[1]  If you do, this is most likely a problem with the sample-app-alpha package,
[1] npm ERR! not with npm itself.
[1] npm ERR! Tell the author that this fails on your system:
[1] npm 
[1] ERR!
[1]      wsrv -o -s -l -p 3000 -x ./server/versions.js
[1] npm ERR! You can get information on how to open an issue for this project with:
[1] npm ERR!     npm bugs sample-app-alpha
[1] npm ERR! Or if that isn't available, you can get their info via:
[1] npm ERR!     npm owner ls sample-app-alpha
[1] npm ERR! There is likely additional logging output above.
[1] 
[1] npm ERR! Please include the following file with any support request:
[1] npm ERR!     /home/dgrumieaux/dev/clients/tsg/projects/alfresco_angular_poc/sample-app-alpha/npm-debug.log
[1] npm run serve exited with code 1
[0] 10:56:25 AM - Compilation complete. Watching for file changes.
```

**Comment by magemello** [comment]
npm run clean 

sorry

**Comment by dgrumieaux** [comment]
Ran all three commands. Same error.

```
[1] > sample-app-alpha@0.1.0 serve /home/dgrumieaux/dev/clients/tsg/projects/alfresco_angular_poc/sample-app-alpha
[1] > wsrv -o -s -l -p 3000 -x ./server/versions.js
[1] 
[0] 
[0] > sample-app-alpha@0.1.0 tsc:w /home/dgrumieaux/dev/clients/tsg/projects/alfresco_angular_poc/sample-app-alpha
[0] > tsc -w
[0] 
[1] Server running at: http://localhost:3000
[1] Opening start page: http://localhost:3000
[1] events.js:160
[1]       throw er; // Unhandled 'error' event
[1]       ^
[1] 
[1] Error: watch /home/dgrumieaux/dev/clients/tsg/projects/alfresco_angular_poc/sample-app-alpha/app/app.routes.ts ENOSPC
[1]     at exports._errnoException (util.js:1026:11)
[1]     at FSWatcher.start (fs.js:1429:19)
[1]     at Object.fs.watch (fs.js:1456:11)
[1]     at createFsWatchInstance (/home/dgrumieaux/dev/clients/tsg/projects/alfresco_angular_poc/sample-app-alpha/node_modules/chokidar/lib/nodefs-handler.js:37:15)
[1]     at setFsWatchListener (/home/dgrumieaux/dev/clients/tsg/projects/alfresco_angular_poc/sample-app-alpha/node_modules/chokidar/lib/nodefs-handler.js:80:15)
[1]     at FSWatcher.NodeFsHandler._watchWithNodeFs (/home/dgrumieaux/dev/clients/tsg/projects/alfresco_angular_poc/sample-app-alpha/node_modules/chokidar/lib/nodefs-handler.js:228:14)
[1]     at FSWatcher.NodeFsHandler._handleFile (/home/dgrumieaux/dev/clients/tsg/projects/alfresco_angular_poc/sample-app-alpha/node_modules/chokidar/lib/nodefs-handler.js:255:21)
[1]     at FSWatcher.<anonymous> (/home/dgrumieaux/dev/clients/tsg/projects/alfresco_angular_poc/sample-app-alpha/node_modules/chokidar/lib/nodefs-handler.js:473:21)
[1]     at FSReqWrap.oncomplete (fs.js:123:15)
[1] 
[1] npm
[1]  ERR! Linux 3.16.0-77-generic
[1] npm ERR! argv "/home/dgrumieaux/.nvm/versions/node/v6.9.1/bin/node" "/home/dgrumieaux/.nvm/versions/node/v6.9.1/bin/npm" "run" "serve"
[1] npm ERR! node v6.9.1
[1] npm ERR!
[1]  npm  v3.10.8
[1] npm ERR! 
[1] code ELIFECYCLE
[1] npm ERR! sample-app-alpha@0.1.0 serve: `wsrv -o -s -l -p 3000 -x ./server/versions.js`
[1] npm ERR! Exit status 1
[1] npm ERR! 
[1] npm ERR! Failed at the sample-app-alpha@0.1.0 serve script 'wsrv -o -s -l -p 3000 -x ./server/versions.js'.
[1] npm 
[1] ERR! Make sure you have the latest version of node.js and npm installed.
[1] npm ERR! If you do, this is most likely a problem with the sample-app-alpha package,
[1] npm ERR! not with npm itself.
[1] npm ERR! Tell the author that this fails on your system:
[1] npm ERR!     wsrv -o -s -l -p 3000 -x ./server/versions.js
[1] npm ERR!
[1]  You can get information on how to open an issue for this project with:
[1] npm ERR!     npm bugs sample-app-alpha
[1] npm ERR! Or if that isn't available, you can get their info via:
[1] npm ERR!     npm owner ls sample-app-alpha
[1] npm ERR! There is likely additional logging output above.
[1] 
[1] npm ERR! Please include the following file with any support request:
[1] npm ERR!     /home/dgrumieaux/dev/clients/tsg/projects/alfresco_angular_poc/sample-app-alpha/npm-debug.log
[1] npm run serve exited with code 1
[0] 11:04:40 AM - Compilation complete. Watching for file changes.
```

**Comment by magemello** [comment]
what operating system are you using?

**Comment by dgrumieaux** [comment]
ubuntu 14.04 LTS

**Comment by magemello** [comment]
it's not the same error, and the ENOSPC error looks strange to me, try to run only:

npm run serve

**Comment by dgrumieaux** [comment]
`npm run serve' results below:
```
> sample-app-alpha@0.1.0 serve /home/dgrumieaux/dev/clients/tsg/projects/alfresco_angular_poc/sample-app-alpha
> wsrv -o -s -l -p 3000 -x ./server/versions.js

events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: watch /home/dgrumieaux/dev/clients/tsg/projects/alfresco_angular_poc/sample-app-alpha ENOSPC
    at exports._errnoException (util.js:1026:11)
    at FSWatcher.start (fs.js:1429:19)
    at Object.fs.watch (fs.js:1456:11)
    at createFsWatchInstance (/home/dgrumieaux/dev/clients/tsg/projects/alfresco_angular_poc/sample-app-alpha/node_modules/chokidar/lib/nodefs-handler.js:37:15)
    at setFsWatchListener (/home/dgrumieaux/dev/clients/tsg/projects/alfresco_angular_poc/sample-app-alpha/node_modules/chokidar/lib/nodefs-handler.js:80:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (/home/dgrumieaux/dev/clients/tsg/projects/alfresco_angular_poc/sample-app-alpha/node_modules/chokidar/lib/nodefs-handler.js:228:14)
    at FSWatcher.NodeFsHandler._handleDir (/home/dgrumieaux/dev/clients/tsg/projects/alfresco_angular_poc/sample-app-alpha/node_modules/chokidar/lib/nodefs-handler.js:407:19)
    at FSWatcher.<anonymous> (/home/dgrumieaux/dev/clients/tsg/projects/alfresco_angular_poc/sample-app-alpha/node_modules/chokidar/lib/nodefs-handler.js:455:19)
    at FSWatcher.<anonymous> (/home/dgrumieaux/dev/clients/tsg/projects/alfresco_angular_poc/sample-app-alpha/node_modules/chokidar/lib/nodefs-handler.js:460:16)
    at FSReqWrap.oncomplete (fs.js:123:15)

npm ERR! Linux 3.16.0-77-generic
npm ERR! argv "/home/dgrumieaux/.nvm/versions/node/v6.9.1/bin/node" "/home/dgrumieaux/.nvm/versions/node/v6.9.1/bin/npm" "run" "serve"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! sample-app-alpha@0.1.0 serve: `wsrv -o -s -l -p 3000 -x ./server/versions.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sample-app-alpha@0.1.0 serve script 'wsrv -o -s -l -p 3000 -x ./server/versions.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the sample-app-alpha package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     wsrv -o -s -l -p 3000 -x ./server/versions.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs sample-app-alpha
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls sample-app-alpha
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/dgrumieaux/dev/clients/tsg/projects/alfresco_angular_poc/sample-app-alpha/npm-debug.log
```

**Comment by magemello** [comment]
ENOSPC means that there is no space on your drive , I think you have to fix this problem, maybe a problem of space or a problem of permission, I can just guess. Try to run the command with sudo to check if is a permission problem.

**Comment by magemello** [comment]
At this point I suggest to run also install with sudo:

sudo npm install

**Comment by magemello** [comment]
Hi @dgrumieaux , do you have any update on this issue?

**Comment by magemello** [comment]
No news after 20 days...closing issue
